repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    -   id: style-files
        args: [--style_fun=tidyverse_style]
    -   id: parsable-R
    -   id: lintr
        args: [--warn_only]
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    -   id: roxygenize
    -   id: codemeta-description-updated
    -   id: use-tidy-description
-   repo: https://github.com/lorenzwalthert/precommit-markdown-link-check
    rev: v0.0.0.9002  # Use the sha / tag you want to point at
    hooks:
    -   id: markdown-link-check
